# Generated by Django 4.1 on 2022-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworldapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
