# Generated by Django 4.1 on 2022-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworldapp', '0002_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_rate',
            name='cash_in',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='currency_rate',
            name='cash_out',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='currency_rate',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='currency_rate',
            name='nowdate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='currency_rate',
            name='nowtime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='currency_rate',
            name='sight_in',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='currency_rate',
            name='sight_out',
            field=models.CharField(default='', max_length=20),
        ),
    ]
