# Generated by Django 4.1 on 2022-12-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myworldapp', '0003_currency_rate_cash_in_currency_rate_cash_out_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency_rate',
            old_name='nowdate',
            new_name='search_date',
        ),
        migrations.RenameField(
            model_name='currency_rate',
            old_name='nowtime',
            new_name='search_time',
        ),
    ]
