# Generated by Django 4.1 on 2022-12-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworldapp', '0008_alter_usd_rate_sight_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usd_rate',
            name='sight_in',
            field=models.CharField(default='', max_length=2),
        ),
    ]
