# Generated by Django 4.1 on 2022-12-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworldapp', '0009_alter_usd_rate_sight_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpy_rate',
            name='cash_out',
            field=models.FloatField(default=''),
        ),
    ]
