# Generated by Django 4.1 on 2023-01-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworldapp', '0010_alter_jpy_rate_cash_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usd_rate',
            name='sight_in',
            field=models.CharField(default='', max_length=20),
        ),
    ]
